### ISSUE TITLE
Just like this.

### ISSUE THREAD

**Issue by Xiaohuang257** [QuiltMC/quilt-installer#18]
The executable jar is a small launcher that will start the Fabric enabled Minecraft server using the versions specified above. There is no need to use an installer when using this method.
https://fabricmc.net/use/server
[I'm Chinese]

**Comment by tennox** [comment]
This is the Quilt repo, not fabric

**Comment by Xiaohuang257** [comment]
> This is the Quilt repo, not fabric

I used the original introduction
[Machine Translation]

**Comment by Xiaohuang257** [comment]
> This is the Quilt repo, not fabric

I used the original introduction
[Machine Translation]

**Comment by tennox** [comment]
I think your translation might be really bad... Maybe try something else?
deepl.com ?
